language: cpp
compiler: gcc
sudo: require
dist: trusty
before_install:
- sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y
- sudo apt-get update -qq
install:
- sudo apt-get -y -qq install libgl1-mesa-dev qt59base qt59imageformats qt59svg qt59charts-no-lgpl qt59tools
- source /opt/qt*/bin/qt*-env.sh
script:
- chmod +x deploy.sh
- ./deploy.sh
after_success:
- curl --upload-file ../Stacer*.AppImage https://transfer.sh/Stacer-x64.AppImage
before_deploy:
- wget -cO lqt "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
- chmod +x lqt
- unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH
- "./lqt dist/stacer/stacer -bundle-non-qt-libs -no-translations"
- cp /opt/qt59/lib/libQt5Svg.so.5.9.0 dist/stacer/lib/libQt5Svg.so.5
- cp /opt/qt59/plugins/imageformats/libqsvg.so dist/stacer/plugins/imageformats
- "./lqt dist/stacer/stacer -appimage"
- rm -f lqt
- mv Stacer-x86_64.AppImage ../Stacer-x_64.AppImage
deploy:
  provider: releases
  api_key:
    secure: EWUytpGgO3xOlL7FRtaCIG9MPlSZWEC/v4xkxlr4eAbpfHVfrusfLVyfKlE7YcNf1gxzzCNLW5EiESElgTe0Rw4DkGdfhIwZ3rKB9ag9NKHQAwv/w6TljCmU4elEF1/nQugq1gKenPNLGQjLBFY5TM4HlaXQK2yr8cxyNV0+lH6EqXLACsPk/LZM9ZxK3xBx4nhvNpy4bqLOBR4zw9zFmoiXF/AgdwSG25RGdM1NxVE/u3hp0wRRXqulE+vTkBj6O+lStm5DZQKHlqgqli9LNVbwTDHudm6K8Rbz6+V0KrxrDEh7YZyohCAyhDD6AsdoyTSht3TXbPgTeCgKL8xvGsxtI8BcUsrhLoSHEynKf2AEnV+XnHVUuNXvvKpFySuOKhfaWELhypqR946P7+BMA2/T8iKisw9wnBLfVM8al/1l4usixJRNamuH7b8hSjZWYkTuci+pbQsd+/ZiX5qCCz6g+SRdPeFaYZgL0hMtHB+34OU+kW7HeY/eM6D5TKlHCZ0o3pY5fNBr7GzQfOkkBxH+hrUsz2zzX60UUF0qcZI5QFmcR6eO0QChIoSTW5iy3zQkVVcClKjxsvqvJPLa6MgJoHFUkyN/C1sY7WZ3mWrxGSjpAiJSyPxLITFGGU0x+66tqicTkaEZaqVcmjGiT4v3Sv9NLAAkO2kWb0oFUGo=
  file: "/home/travis/build/atakanprofile/Stacer-x_64.AppImage"
  on:
    repo: atakanprofile/Stoc
    branch: native
    tags: true

