language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y
    - sudo apt-get update -qq

install:
    - sudo apt-get -y -qq install qt5-default libgl1-mesa-dev qt59base qt59imageformats qt59svg qt59charts-no-lgpl qt59tools
    - source /opt/qt*/bin/qt*-env.sh
    - wget -cO lqt "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
    - chmod +x lqt
    
script:
    - chmod +x deploy.sh && ./deploy.sh
    - unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH
    - ./lqt dist/stacer/stacer -bundle-non-qt-libs -no-translations
    - cp -a $QTDIR/lib/$(readlink $QTDIR/lib/libQt5Svg.so.5) dist/stacer/stacer/lib/libQt5Svg.so.5
    - ./lqt dist/stacer/stacer -appimage

after_success:
    - curl --upload-file ./Stacer*.AppImage https://transfer.sh/Stacer-xx64.AppImage
